sudo: required
language: generic

services:
- docker

before_install:
- docker build -t abaranov/react-test -f ./client/Dockerfile.dev ./client

script:
- docker run -e CI=True abaranov/react-test npm test -- --coverage

after_success:
- docker build -t abaranov/multi-client ./client
- docker build -t abaranov/multi-nginx ./nginx
- docker build -t abaranov/multi-server ./server
- docker build -t abaranov/multi-worker ./worker
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
# Pushing images to dockerhub
- docker push abaranov/multi-client
- docker push abaranov/multi-nginx 
- docker push abaranov/multi-server
- docker push abaranov/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ca-central-1-908698488443"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
